SELECT NAME, usersTable.USER_ID, COALESCE(
(SELECT COUNT(*) FROM `PhotoPortalDB`.PHOTO_POSTS
	JOIN `PhotoPortalDB`.USERS ON USERS.USER_ID = PHOTO_POSTS.USER_ID
	WHERE DAY(PHOTO_POSTS.CREATION_DATE) = 9
			AND MONTH(PHOTO_POSTS.CREATION_DATE) = 5
			AND PHOTO_POSTS.USER_ID = usersTable.USER_ID
	), 0) as 'Posts Count'
	FROM `PhotoPortalDB`.PHOTO_POSTS
	RIGHT JOIN `PhotoPortalDB`.USERS as usersTable ON usersTable.USER_ID = PHOTO_POSTS.USER_ID
	GROUP BY usersTable.USER_ID