SELECT USERS.NAME FROM `PhotoPortalDB`.USERS
	JOIN `PhotoPortalDB`.PHOTO_POSTS ON USERS.USER_ID = PHOTO_POSTS.USER_ID
	WHERE DATE(PHOTO_POSTS.CREATION_DATE) = DATE(NOW())
    GROUP BY USERS.NAME
    HAVING COUNT(PHOTO_POSTS.POST_ID) > 3