SELECT USERS.NAME, DATE_FORMAT(PHOTO_POSTS.CREATION_DATE, '%k:%i') as time, PHOTO_POSTS.DESCRIPTION
	FROM `PhotoPortalDB`.PHOTO_POSTS
	JOIN `PhotoPortalDB`.USERS ON USERS.USER_ID = PHOTO_POSTS.USER_ID
    ORDER BY PHOTO_POSTS.CREATION_DATE